services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"  # Контейнер 1 слушает на порту 8080

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:80"  # Контейнер 2 слушает на порту 8081